sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
    - travis_retry pip install coveralls
    - pip install -e .[testing]
script:
- nosetests -v
after_success: 
  coveralls
